--- 
 - name: add users and groups
   hosts: all
   become: yes
   vars:
     password: redhat
   tasks:
     - name: add user name greta
       user: 
         name: greta
     - name: add user amit with password
       ansible.builtin.user: 
         name: amit
         password: "{{ password | password_hash('sha512') }}"
         update_password: on_create
     - name: add group name devops
       group:
         name: devops
         state: present
     - name: add user ashish and add them to group devops
       user:
         name: ashish
         groups: devops
         append: yes
     - name: add user rahul and generate ssh keys
       user: 
         name: rahul 
         generate_ssh_key: yes
         ssh_key_bits: 2048
         ssh_key_file: .ssh/id_rsa
     - name: add user noHome with no home directory and account expire on certain date
       user:
         name: noHome
         create_home: no
         expires: 100
     - name: add a user suraj having login shell as /bin/sh and add them to group devops
       user:
         name: suraj
         shell: /bin/bash
         groups: devops
         append: yes
     - name: add user 'Vijay Sharma' with a specific uid 1077, having direc. as /home/vijaysharma
       user: 
         name: vijay
         comment: vijay sharma
         uid: 1077
         createhome: yes
         home: /home/vijaysharma
      
    
